# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_auto_20170417_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='forumPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='newsfeed.ForumPost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='newsPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='newsfeed.Post'),
        ),
    ]
