# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0007_auto_20170418_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='awayTeamScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='homeTeamScore',
            field=models.IntegerField(default=0),
        ),
    ]
