# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0009_auto_20170418_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_posts', to='newsfeed.Team'),
        ),
    ]
