# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_post_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.ForeignKey(blank=True, default='All', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_posts', to='newsfeed.Team'),
        ),
    ]
